{
  "name": "mbiopay",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "license": "MIT",  // <--- Add this line
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    ...
  }
}

