services:
  # 1. Frontend Service (Static Site)
  - type: web           # Change from 'static' to 'web'
    name: my-frontend
    runtime: static     # This defines it as a Static Site
    rootDir: apps/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist  # Use 'staticPublishPath' for static sites
    buildFilter:
      paths:
        - apps/frontend/**
      ignoredPaths:
        - apps/frontend/README.md
